openapi: 3.0.3
info:
  title: Chat App API - Messages Service
  description: API for a chat app that handles messages.
  version: 1.0.0
servers:
- url: localhost:3001/api/v1
  description: Local server
paths:
  /messages:
    post:
      summary: Send a new message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
            examples:
              textMessage:
                value:
                  senderId: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                  receiverId: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                  timestamp: "2023-04-12T23:20:50.52Z"
                  messageType: "text"
                  textContent: "Hello, how are you?"
      responses:
        201:
          description: Message sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        400:
          description: Invalid input

    get:
      summary: Retrieve paginated messages for a sender and receiver
      parameters:
        - name: senderId
          in: query
          required: true
          schema:
            type: string
            format: uuid
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        - name: receiverId
          in: query
          required: true
          schema:
            type: string
            format: uuid
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
          example: 1
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            default: 25
          example: 25
      responses:
        200:
          description: Messages retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
        400:
          description: Invalid input

components:
  schemas:
    Message:
      type: object
      required:
        - senderId
        - receiverId
        - timestamp
        - messageType
      properties:
        messageId:
          type: string
          format: uuid
          description: A unique identifier for the message
        senderId:
          type: string
          format: uuid
          description: The ID of the user who sent the message
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        receiverId:
          type: string
          format: uuid
          description: The ID of the user who received the message
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        timestamp:
          type: string
          format: date-time
          description: The time when the message was sent
          example: "2023-04-12T23:20:50.52Z"
        messageType:
          type: string
          enum: [text, photo, video]
          description: The type of message (text, photo, or video)
          example: "text"
        textContent:
          type: string
          nullable: true
          description: The text content of the message (if applicable)
          example: "Hello, how are you?"
